### ISSUE TITLE
setBounds and setPosition sometimes does not work after map creation

### ISSUE THREAD

**Issue by iori57** [victorzimmer/MapKit#4]
After calling .createMap, I tried to call setBounds and setPosition immediately and it works.

However after it a while when I try calling them again, it does not work anymore and I debugged until the objective-C code 'changeMapBounds' somehow mapView returns nil on the line:

MKMapView\* mapView = [self.webView viewWithTag:mapId];

Checked the mapId and it was exactly the same with the one I used to create it.

Still debugging to find out more but just wondering if anyone knows what could be happening. Maybe my webview was altered without my knowledge?

Using version 0.0.3

**Comment by iori57** [comment]
I found the issue, this is because mapId is a NSString, and it is being converted to NSInteger when being used in the line:

MKMapView\* mapView = [self.webView viewWithTag:mapId];

And the conversion gives different values depending on memory allocation I think..

Hence it couldn't find the mapView for my case.

@victorzimmer is fixing the issue I think, I saw a couple of commits in Development branch with comment 'Fixed mapId'

**Comment by victorzimmer** [comment]
My fault for not reading the Apple Docs well enough :P 
Seemingly UIView tags can only be of type NSNumber (No idea why Xcode didn't complain).

Anyways, should be okay now. Please try it and see if it works for you!

**Comment by iori57** [comment]
I can confirm this works now in the latest commit in master :+1:

**Comment by victorzimmer** [comment]
Awesome. I'll close the issue. 

For reference it was solved by using the maps arrayId (numeric value) instead of the actual mapId (string) in all references to Objective-C. Of course the API stays exactly the same as both variables are still kept in the same way in all global MapKit objects.
