### ISSUE TITLE
Some issues with mapkit.js

### ISSUE THREAD

**Issue by iori57** [victorzimmer/MapKit#6]
Thought you might want to take note that I need to make some minor changes below for the plugin to work:
- Replaced ASCII character ` with ' if not it will throw application error on my side
- Replaced Number.isFinite() with isFinite()

Not sure why the second one gives problems on runtime though, as it normally works

**Comment by victorzimmer** [comment]
` is used for template strings, it requires ECMAScript 6 or higher, but for Cordova that should be ok.

No idea why Number.isFinite() wouldn't work, I've never had any issues with it.
What line did you change? :)

**Comment by iori57** [comment]
I am not sure myself, but when I leave ` in the code it gives Application Error on runtime when trying to run on the iPhone 6 plus. I am using cordova version 3.8.0

For Number.isFinite(), it throws Application Error on runtime
Javascript Error | Message: [ TypeError: undefined is not a function (evaluating 'Number.isFinite(arguments[0])') ]

Changing to just isFinite() works, on line 167 and 215

**Comment by iori57** [comment]
On a side note, xcode is giving a bunch of warnings in MapKit.m, is it something to worry about? Something like below:

'success:callbackId:' is deprecated: Deprecated in Cordova 3.6. Use the CDVCommandDelegate equivalent of sendPluginResult:callbackId. This will be removed in 4.0.0

**Comment by victorzimmer** [comment]
So according to MDN both Number.isFinite() and ` are new in ES6

MapKit was built with my local version of Cordova (3.9.2)

However as far as I know the ECMAScript version is related to the platform, not the Cordova version...

**Comment by victorzimmer** [comment]
Not sure about these deprecated messages...

**Comment by victorzimmer** [comment]
@iori57 are you testing with iOS 8 or iOS 9?

**Comment by victorzimmer** [comment]
Should be fixed now. I'm assuming you were testing with iOS 8 as it was missing complete ES6 support.

Please confirm that the latest commit in master fixes the issue.

**Comment by iori57** [comment]
Yup I am on iOS 8. Tested and confirmed that the latest commit fixed the issue. Thanks a bunch!

**Comment by victorzimmer** [comment]
No problem. Thanks for taking the time to report bugs.

I kinda thought ES6 would be safe with Cordova, but seemingly iOS 8 and earlier does not implement it in their WebViews. Same seems to apply to all versions of Android. I guess I'll stick with ES5 then.
